/*
 * ble_server.c — BLE GATT server for the Pico W keyboard bridge.
 *
 * Uses BTstack exclusively (no TinyUSB here to avoid HID type conflicts).
 * Receives text via WRITE on the Digital Output characteristic and makes
 * it available to the main loop via a simple ring buffer.
 */
#include "pico/cyw43_arch.h"
#include "pico/btstack_cyw43.h"

#include "btstack.h"

/* doorbell.h generated by pico_btstack_make_gatt_header from doorbell.gatt */
#include "doorbell.h"

#include "ble_server.h"

#define HEARTBEAT_PERIOD_MS 1000
#define APP_AD_FLAGS 0x06
#define BLE_NAME "Pico-KB-Bridge"

/* Advertising data */
static uint8_t adv_data[] = {
    0x02, BLUETOOTH_DATA_TYPE_FLAGS, APP_AD_FLAGS,
    0x17, BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME,
    'P','i','c','o','-','K','B','-','B','r','i','d','g','e',
    0x03, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_16_BIT_SERVICE_CLASS_UUIDS,
    0xE0, 0xFF,
};
static const uint8_t adv_data_len = sizeof(adv_data);

static hci_con_handle_t con_handle = HCI_CON_HANDLE_INVALID;

/* Ring buffer for characters received via BLE */
#define BLE_Q_LEN 64
static volatile char ble_q[BLE_Q_LEN];
static volatile uint8_t ble_r = 0, ble_w = 0;

static bool ble_q_push(char c) {
    uint8_t n = (ble_w + 1) & (BLE_Q_LEN - 1);
    if (n == ble_r) return false;
    ble_q[ble_w] = c;
    ble_w = n;
    return true;
}

static bool ble_q_pop(char *c) {
    if (ble_r == ble_w) return false;
    *c = ble_q[ble_r];
    ble_r = (ble_r + 1) & (BLE_Q_LEN - 1);
    return true;
}

/* HCI event handler */
static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    UNUSED(channel);
    UNUSED(size);

    if (packet_type != HCI_EVENT_PACKET) return;

    switch (hci_event_packet_get_type(packet)) {
        case HCI_EVENT_LE_META: {
            uint8_t subevent = hci_event_le_meta_get_subevent_code(packet);
            if (subevent == HCI_SUBEVENT_LE_CONNECTION_COMPLETE) {
                con_handle = hci_subevent_le_connection_complete_get_connection_handle(packet);
            }
            break;
        }

        case HCI_EVENT_DISCONNECTION_COMPLETE:
            con_handle = HCI_CON_HANDLE_INVALID;
            break;

        default:
            break;
    }
}

/* ATT write callback: receives text from BLE client */
static int att_write_callback(hci_con_handle_t connection_handle,
                              uint16_t att_handle, uint16_t transaction_mode,
                              uint16_t offset, uint8_t *buffer, uint16_t buffer_size) {
    UNUSED(connection_handle);
    UNUSED(transaction_mode);
    UNUSED(offset);

    if (att_handle == ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DIGITAL_OUTPUT_01_VALUE_HANDLE) {
        for (uint16_t i = 0; i < buffer_size; i++) {
            ble_q_push((char)buffer[i]);
        }
        return 0;
    }

    return 0;
}

void ble_server_init(void) {
    l2cap_init();
    sm_init();
    att_server_init(profile_data, NULL, att_write_callback);

    /* Register HCI event handler */
    static btstack_packet_callback_registration_t hci_event_callback_registration;
    hci_event_callback_registration.callback = &packet_handler;
    hci_add_event_handler(&hci_event_callback_registration);

    att_server_register_packet_handler(packet_handler);

    /* Configure advertising */
    gap_advertisements_set_data(adv_data_len, adv_data);
    gap_advertisements_enable(1);
}

bool ble_server_connected(void) {
    return con_handle != HCI_CON_HANDLE_INVALID;
}

/* Pop a character from the BLE receive queue (called from main loop) */
bool ble_server_get_char(char *c) {
    return ble_q_pop(c);
}
